backend:
  name: git-gateway
  branch: master

media_folder: "/src/static/uploads"
public_folder: "/src/static/uploads"
site_url: https://www.charlotteultra.com
display_url: https://charlotteultra.com
logo_url: https://charlotteultra.com/static/swimmac-logo.svg

collections:
  - name: "pages"
    label: "Page Content"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "pages.njk"

      - label: "permalink"
        name: "permalink"
        widget: "hidden"
        default: false

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Post Body"
        name: "body"
        widget: "markdown"